#!/bin/bash
# Vercel Environment Variables Setup Guide
# Run this to see exactly what needs to be added to Vercel

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     Vercel Environment Variables - COPY THESE              ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "🔧 Go to: https://vercel.com/dashboard"
echo "   → Select your project"
echo "   → Settings → Environment Variables"
echo ""
echo "Add these variables (one at a time):"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. SUPABASE_URL"
echo "   Value: https://rjxdxpegpclglkvybpej.supabase.co"
echo "   Environment: Production ✓"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "2. SUPABASE_SERVICE_KEY"
echo "   Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqeGR4cGVncGNsZ2xrdnlicGVqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2OTAyMTYxOSwiZXhwIjoyMDg0NTk3NjE5fQ.PUKIySWqBuWuHvZ6A1H6KE3E1Cn7GC1f_IojtCoWD9k"
echo "   Environment: Production ✓"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "3. ADMIN_PASSWORD"
echo "   Value: admin123"
echo "   Environment: Production ✓"
echo "   ⚠️  Change this to a secure password!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "4. ADMIN_EMAIL"
echo "   Value: invest@arterycapital.com"
echo "   Environment: Production ✓"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "5. FROM_EMAIL"
echo "   Value: Artery Capital <noreply@arterycapital.com>"
echo "   Environment: Production ✓"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "6. NEXT_PUBLIC_APP_URL (Find your Vercel URL first!)"
echo "   Value: https://your-app-name.vercel.app"
echo "   Environment: Production ✓"
echo "   📝 Replace 'your-app-name' with your actual Vercel domain"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "7. RESEND_API_KEY (OPTIONAL - for email notifications)"
echo "   Value: [Get from https://resend.com]"
echo "   Environment: Production ✓"
echo "   Note: Leave empty for now, app works without it"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ After adding all variables:"
echo "   1. Vercel will automatically redeploy"
echo "   2. Wait 2-3 minutes for deployment"
echo "   3. Visit your Vercel URL and test!"
echo ""
echo "🔗 Your Vercel URL will be shown in the Vercel dashboard"
echo "   Format: https://your-project-name.vercel.app"
echo ""
