-- ============================================================
-- Artery Wealth Builder — On-Chain Signal Engine Schema
-- Prefixed with onchain_ to avoid colliding with the existing
-- Node.js signals table used by the trading dashboard.
-- Run against your live Supabase project.
-- ============================================================

-- 1. Raw on-chain signals generated by the signal engine
CREATE TABLE IF NOT EXISTS onchain_signals (
  id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  signal_type     TEXT NOT NULL CHECK (signal_type IN (
                    'whale_accumulation', 'vol_mean_reversion',
                    'stablecoin_flows', 'liquidation_cascade'
                  )),
  asset           TEXT NOT NULL CHECK (asset IN ('BTC', 'ETH')),
  signal_date     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  confidence_score DECIMAL(5, 4) NOT NULL CHECK (confidence_score BETWEEN 0 AND 1),
  direction       TEXT NOT NULL CHECK (direction IN ('BULLISH', 'BEARISH', 'NEUTRAL')),
  signal_data     JSONB NOT NULL DEFAULT '{}',
  expires_at      TIMESTAMP WITH TIME ZONE,   -- signal decay window
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_onchain_signals_asset_date
  ON onchain_signals (asset, signal_date DESC);
CREATE INDEX IF NOT EXISTS idx_onchain_signals_type
  ON onchain_signals (signal_type);
CREATE INDEX IF NOT EXISTS idx_onchain_signals_expires
  ON onchain_signals (expires_at);

-- 2. Cross-validation of each signal against each strategy
CREATE TABLE IF NOT EXISTS signal_strategy_confirmations (
  id                        UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  signal_id                 UUID NOT NULL REFERENCES onchain_signals (id) ON DELETE CASCADE,
  strategy_name             TEXT NOT NULL CHECK (strategy_name IN (
                              'momentum', 'mean_reversion', 'breakout', 'multi_strategy'
                            )),
  strategy_condition_met    BOOLEAN NOT NULL,
  strategy_confidence       DECIMAL(5, 4),            -- strategy's own confidence before boost
  signal_boosted_confidence DECIMAL(5, 4),            -- confidence after signal augmentation
  boost_amount              DECIMAL(5, 4) DEFAULT 0,  -- positive = boost, negative = caution
  confirmation_details      JSONB DEFAULT '{}',        -- which conditions passed/failed
  created_at                TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ssc_signal_id
  ON signal_strategy_confirmations (signal_id);
CREATE INDEX IF NOT EXISTS idx_ssc_strategy
  ON signal_strategy_confirmations (strategy_name);

-- 3. Executions triggered by signal + strategy confirmation
CREATE TABLE IF NOT EXISTS signal_executions (
  id                  UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  signal_id           UUID NOT NULL REFERENCES onchain_signals (id) ON DELETE CASCADE,
  execution_strategy  TEXT NOT NULL,   -- momentum | mean_reversion | breakout | multi_strategy
  coinbase_order_id   TEXT,
  asset               TEXT NOT NULL,
  side                TEXT NOT NULL CHECK (side IN ('BUY', 'SELL')),
  size                DECIMAL(18, 8) NOT NULL,
  entry_price         DECIMAL(18, 8) NOT NULL,
  entry_time          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  exit_price          DECIMAL(18, 8),
  exit_time           TIMESTAMP WITH TIME ZONE,
  pnl                 DECIMAL(18, 8),
  pnl_pct             DECIMAL(8, 4),
  stop_loss           DECIMAL(18, 8),
  take_profit         DECIMAL(18, 8),
  status              TEXT DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'CLOSED', 'CANCELLED')),
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_signal_executions_signal
  ON signal_executions (signal_id);
CREATE INDEX IF NOT EXISTS idx_signal_executions_status
  ON signal_executions (status);

-- 4. Daily market data snapshots (raw inputs used to calculate signals)
CREATE TABLE IF NOT EXISTS market_data_snapshots (
  id                  UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  data_date           DATE NOT NULL,
  asset               TEXT NOT NULL CHECK (asset IN ('BTC', 'ETH')),
  exchange_inflow     DECIMAL(18, 4),    -- USD value flowing INTO exchanges
  exchange_outflow    DECIMAL(18, 4),    -- USD value flowing OUT of exchanges
  whale_transactions  INTEGER,           -- count of txns > threshold
  realized_vol        DECIMAL(8, 6),     -- annualised realised vol (0-1)
  funding_rate        DECIMAL(8, 6),     -- perpetual funding rate
  stablecoin_inflow   DECIMAL(18, 4),    -- USD stablecoin flowing to exchanges
  liquidation_volume  DECIMAL(18, 4),    -- USD liquidated in window
  open_interest       DECIMAL(18, 4),    -- futures open interest
  price_close         DECIMAL(18, 8),    -- closing price for the day
  volume_24h          DECIMAL(18, 4),    -- 24h volume in USD
  data_sources        JSONB DEFAULT '{}', -- which APIs contributed each field
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE (data_date, asset)
);

CREATE INDEX IF NOT EXISTS idx_mds_date_asset
  ON market_data_snapshots (data_date DESC, asset);

-- 5. Tunable thresholds per signal type
CREATE TABLE IF NOT EXISTS signal_thresholds (
  id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  signal_type     TEXT NOT NULL,
  asset           TEXT NOT NULL,
  threshold_key   TEXT NOT NULL,
  threshold_value DECIMAL(10, 6) NOT NULL,
  description     TEXT,
  active          BOOLEAN DEFAULT TRUE,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE (signal_type, asset, threshold_key)
);

-- Default thresholds
INSERT INTO signal_thresholds (signal_type, asset, threshold_key, threshold_value, description) VALUES
  -- Whale accumulation
  ('whale_accumulation', 'BTC', 'outflow_velocity_min',    0.30, 'Minimum outflow velocity to trigger'),
  ('whale_accumulation', 'BTC', 'stablecoin_boost_ratio',  1.50, 'Stablecoin inflow ratio to boost whale score'),
  ('whale_accumulation', 'BTC', 'min_confidence',          0.55, 'Minimum confidence to emit signal'),
  ('whale_accumulation', 'ETH', 'outflow_velocity_min',    0.30, 'Minimum outflow velocity to trigger'),
  ('whale_accumulation', 'ETH', 'stablecoin_boost_ratio',  1.50, 'Stablecoin inflow ratio to boost whale score'),
  ('whale_accumulation', 'ETH', 'min_confidence',          0.55, 'Minimum confidence to emit signal'),
  -- Vol mean reversion
  ('vol_mean_reversion', 'BTC', 'vol_spike_ratio',         1.50, 'Realized vol multiple over 30d avg'),
  ('vol_mean_reversion', 'BTC', 'funding_rate_min',        0.0005, 'Min funding rate (0.05%)'),
  ('vol_mean_reversion', 'BTC', 'min_confidence',          0.50, 'Minimum confidence to emit signal'),
  ('vol_mean_reversion', 'ETH', 'vol_spike_ratio',         1.50, 'Realized vol multiple over 30d avg'),
  ('vol_mean_reversion', 'ETH', 'funding_rate_min',        0.0005, 'Min funding rate (0.05%)'),
  ('vol_mean_reversion', 'ETH', 'min_confidence',          0.50, 'Minimum confidence to emit signal'),
  -- Stablecoin flows
  ('stablecoin_flows',  'BTC', 'z_score_min',              2.00, 'Minimum z-score deviation'),
  ('stablecoin_flows',  'BTC', 'min_confidence',           0.60, 'Minimum confidence to emit signal'),
  ('stablecoin_flows',  'ETH', 'z_score_min',              2.00, 'Minimum z-score deviation'),
  ('stablecoin_flows',  'ETH', 'min_confidence',           0.60, 'Minimum confidence to emit signal'),
  -- Liquidation cascade
  ('liquidation_cascade', 'BTC', 'liq_spike_ratio',        3.00, 'Liquidation multiple over 5d avg'),
  ('liquidation_cascade', 'BTC', 'min_confidence',         0.45, 'Minimum confidence to emit signal'),
  ('liquidation_cascade', 'ETH', 'liq_spike_ratio',        3.00, 'Liquidation multiple over 5d avg'),
  ('liquidation_cascade', 'ETH', 'min_confidence',         0.45, 'Minimum confidence to emit signal')
ON CONFLICT (signal_type, asset, threshold_key) DO NOTHING;

-- RLS — service role has full access
ALTER TABLE onchain_signals               ENABLE ROW LEVEL SECURITY;
ALTER TABLE signal_strategy_confirmations ENABLE ROW LEVEL SECURITY;
ALTER TABLE signal_executions             ENABLE ROW LEVEL SECURITY;
ALTER TABLE market_data_snapshots         ENABLE ROW LEVEL SECURITY;
ALTER TABLE signal_thresholds             ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role full access on onchain_signals"
  ON onchain_signals FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on signal_strategy_confirmations"
  ON signal_strategy_confirmations FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on signal_executions"
  ON signal_executions FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on market_data_snapshots"
  ON market_data_snapshots FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on signal_thresholds"
  ON signal_thresholds FOR ALL TO service_role USING (true) WITH CHECK (true);
